// src/components/MyHoverableComponent.svelte
<script>
    import Tooltip from './Tooltip.svelte';
    import TooltipContent from './TooltipContent.svelte';
    let isHovering = false;
    let count = 0;
    function onClick() {
        console.log('Clicked!');
        count += 1;
    }
</script>

<div
    class="root"
    class:hovering={isHovering}
    onmouseover={() => isHovering = true}
    onmouseout={() => isHovering = false}
    onclick={onClick}
>
    HELLO WORLD!
    Count: {count}
  {#if isHovering}
    <Tooltip>
      <TooltipContent />
    </Tooltip>
  {/if}
</div>

<style>
.root {
    width: 200px;
    height: 200px;
    background-color: #f0f0f0;
}
</style>

// src/components/MyHoverableComponent.tsx
import { useCallback, useState } from "react";
import Tooltip from "./Tooltip";
import TooltipContent from "./TooltipContent";
import styles from "./MyHoverableComponent.module.css";

export default function HelloBox() {
	const [isHovering, setIsHovering] = useState(false);
	const [count, setCount] = useState(0);

	const onClick = useCallback(() => {
		console.log("Clicked!");
		setCount((c) => c + 1);
	}, []);

	return (
		<div
			className={`${styles.root} ${isHovering ? styles.hovering : ""}`}
			onMouseEnter={() => setIsHovering(true)}
			onMouseLeave={() => setIsHovering(false)}
			onClick={onClick}
		>
			<div>HELLO WORLD!</div>
			<div>Count: {count}</div>

			{isHovering && (
				<Tooltip>
					<TooltipContent />
				</Tooltip>
			)}
		</div>
	);
}
